//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientRecordEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patientrecord
    {
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string bloodType { get; set; }
        public string medicalCondition { get; set; }
        public Nullable<System.DateTime> dateOfAdmission { get; set; }
        public string doctor { get; set; }
        public string hospital { get; set; }
        public string insuranceProvider { get; set; }
        public Nullable<decimal> billingAmount { get; set; }
        public Nullable<int> roomNumber { get; set; }
        public string admissionType { get; set; }
        public Nullable<System.DateTime> dischargeDate { get; set; }
        public string medication { get; set; }
        public string testResults { get; set; }
    }
}
